### ISSUE TITLE
No module named 'humanize'

### ISSUE THREAD

**Issue by ghost** [dmuth/s3-disk-usage#1]
Traceback (most recent call last):
  File "./2-process-bucket-contents.py", line 15, in <module>
    import humanize
ImportError: No module named 'humanize'

**Comment by ghost** [comment]
Looks like for the newb here this is resolved after using virtualenv instead of flailing around like a fish out of water.

**Comment by dmuth** [comment]
Yep, `virtualenv` will work.  You can also run `pip install -r requirements.txt` without `virtualenv`.

I'll close this out since it sounds like you got it working, but feel free to re-open it if not.

-- Doug

**Comment by ghost** [comment]
Thanks, all set to keep closed.
