### ISSUE TITLE
KeyError 'DeleteMarkers

### ISSUE THREAD

**Issue by ghost** [dmuth/s3-disk-usage#2]
2018-07-03 15:34:56,185: INFO: Args: Namespace(file='jenn-l-charts.json', humanize=True)
Traceback (most recent call last):
  File "./2-process-bucket-contents.py", line 341, in <module>
    main(args.file)
  File "./2-process-bucket-contents.py", line 328, in main
    delete_markers = processDeletes(data["DeleteMarkers"])
KeyError: 'DeleteMarkers

**Comment by ghost** [comment]
Had to bypass this section by commenting out:
**delete_markers = processDeletes(data["DeleteMarkers"])**
And updating:
**data = combineDeletedAndVersions(versions, versions)**

**Comment by dmuth** [comment]
Hmm... interesting.  Is this something that you can reproduce reliably?  If so, please let me know what I can do to make it happen on my end.

Thanks,

-- Doug

**Comment by ghost** [comment]
Actually I think it works now. I manually deleted a file. Also I made the aws configure region match the s3 region. In addition, I have versioning turned on, is this required?

 Present:            num_files: 47,631
   Present:         num_versions: 47,631
   Present:         average_size: 2.8K
   Present:          latest_size: 131.4M
   Present:           total_size: 131.4M
   Present:   pct_used_by_latest: 100.0%

   Deleted:            num_files: 1
   Deleted:         num_versions: 1
   Deleted:         average_size: 1.6K
   Deleted:           total_size: 1.6K

**Comment by dmuth** [comment]
Hey, sorry for taking so long to answer this--this came in while I was on vacation, and the email for it got pushed down in my inbox.

To answer the question, versioning *was* required, but I just wrote a fix so that my script also works when versioning is not turned on, and will commit shortly.

-- Doug
